variables:
    SolutionBaseName: 'NCS.DSS.Contact'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (CDH)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

jobs:
# Build the app with the dfc-dotnetcore-build template. 
- job: BuildDotNetStandard
  displayName: Build-DotNetStandard
  dependsOn: TestBranchName
  condition: and(succeeded(), eq(dependencies.TestBranchName.outputs['ExecuteTestBranchNameScript.FunctionAppVersion'], 'Version2+'))

  steps:
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcorefunctionapp-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)





